#!/bin/sh
# prerm script for domtrix-lb

set -e

# Upgrade restart bypass

if [ "$1" = "upgrade" -a -f /etc/domtrix/norestart ]
then
    :
else
    # Stop workers using domtrix
    magic_word="domtrix-(lb|mys|service)-worker"
    job_list="$(grep -E -l "${magic_word}" /etc/init/*|sed 's|^/etc/init/\(.*\).conf$|\1|')"
    for job in ${job_list}
    do
	    echo "Stopping ${job}"
	    stop ${job} || true
    done
fi

#DEBHELPER#

exit 0
